function test() {
  throw "thrown exception";
}
